---
abstract: 'Morph data from one source to another'
author:
  - 'Nicholas R. Perez <nperez@cpan.org>'
build_requires:
  DBD::SQLite: 0
  DBIx::Class::Core: 0
  DBIx::Class::Schema: 0
  Test::More: 0
  Try::Tiny: 0
  base: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Morph
requires:
  DBIx::Class: 0
  Data::DPath: 0
  Devel::PartialDump: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Params::Validate: 0
  MooseX::Role::Parameterized: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Structured: 0
  SQL::Translator: 0.11006
  Scalar::Util: 0
  namespace::autoclean: 0
resources:
  repository: git://github.com/nperez/data-morph.git
version: 1.113270
